export const THEMES = [
  "Blood Moon",
  "Coven",
  "Dark Star",
  "Dawnbringer",
  "Nightbringer",
  "Dragonmancer",
  "Elderwood",
  "Empyrean",
  "High Noon",
  "Inkshadow",
  "Mecha Kingdoms",
  "Odyssey",
  "Omega Squad",
  "Pool Party",
  "PROJECT",
  "PsyOps",
  "Pulsefire",
  "Ruined",
  "Sentinel",
  "Soul Fighter",
  "Spirit Blossom",
  "Star Guardian",
  "Winterblessed",
  "Arcade",
  "Battle Academia",
  "Cafe Cuties",
  "Space Groove",
];
