// Champions are now fetched dynamically from Riot API
export const THEMES = [
  "Blood Moon",
  "Coven",
  "Cyberpop",
  "Dark Star",
  "Dawnbringer",
  "Demacia Vice",
  "Dragonmancer",
  "Elderwood",
  "Empyrean",
  "High Noon",
  "Inkshadow",
  "Mecha Kingdoms",
  "Nightbringer",
  "Odyssey",
  "Omega Squad",
  "Pool Party",
  "PROJECT",
  "PsyOps",
  "Pulsefire",
  "Ruined",
  "Sentinel",
  "Soul Fighter",
  "Spirit Blossom",
  "Star Guardian",
  "Winterblessed",
];
